### ISSUE TITLE
MQTT: Out of mem

### ISSUE THREAD

**Issue by miolion** [martin-ger/esp_mqtt#15]
Hi,

I think this is very useful project for small IoT devices.
I have found a minor issue if a client give NULL password to the broker...

For examble,
> mosquitto_sub -h 192.168.4.1 -d -u "user" **-P ""** -t hello
> mosquitto_pub -h 192.168.4.1 -u "user" **-P ""** -t hello -m message

There are always "MQTT: Out of mem" in the debug log due to the following conditions in mqtt_server.c at line number 532.

>    if (password != NULL)
>        clientcon->connect_info.password = (char *)os_zalloc(password_len+1);
>    if (clientcon->connect_info.password != NULL) { ...

In that case, the value of 'clientcon->connect_info.password' will be always NULL.

SJ

**Comment by miolion** [comment]
[mqtt_server.c.zip](https://github.com/martin-ger/esp_mqtt/files/1469981/mqtt_server.c.zip)

The attached is the modified of mine ...

SJ

**Comment by martin-ger** [comment]
Thanks for the report! This we just have to skip the "if (password != NULL)". Think it left over in the code from former editing.

**Comment by miolion** [comment]
Yes, or this could be like this,

		if (password == NULL) {
		    MQTT_WARNING("MQTT: Password invalid\r\n");
		    MQTT_server_disconnectClientCon(clientcon);
		    return;
		}

		clientcon->connect_info.password = (char *)os_zalloc(password_len+1);

The final modification decision will be up to you,

SJ

**Comment by miolion** [comment]
I have found out that Martin has resolved this issue.
