### ISSUE TITLE
PlatformIO flashing?

### ISSUE THREAD

**Issue by starkillerOG** [martin-ger/esp_mqtt#18]
I am farly new to programming an ESP8266, so it might be a dump question.
Is it possible to flash this firmware to the ESP using PlatformIO?

**Comment by starkillerOG** [comment]
I run PlarformIO within Atom, but I am not verry fimilliar with both.
Is there a more detailed step by step guide how to flash this software to the esp?

**Comment by martin-ger** [comment]
No experience (and idea) with PlattformIO, but there is a description at https://github.com/martin-ger/esp_mqtt#building-and-flashing . 

How to connect and setup your ESP8266 heavily depends on your modul (I would recommend a NodeMCU or Wemos D1 Mini). You find lots of tutorial on youtube on how to get the serial connection for any kind of modul - after that you can use the download tool from the link above.

**Comment by starkillerOG** [comment]
@martin-ger Thanks for the information.
Can you also build/compile the code with the "ESP8266 Download Tool"?
Or which program can I use to build/compile the changes to the "user_config.h" file such as my routers ssid and pasword?

**Comment by martin-ger** [comment]
Top build the software you will never the esp-open-sdk. Have auch look in 
the "build" section of the Readme.


Am 27. November 2017 11:53:50 nachm. schrieb starkillerOG 
<notifications@github.com>:
