### ISSUE TITLE
ssid with spaces

### ISSUE THREAD

**Issue by msillano** [martin-ger/esp_mqtt#21]
My wifi AP is "FRITZ!Box 3272", but the command 'set ssid' cut it.
transcript:
   scandone
   no FRITZ!Box found, reconnect after 1s
   disconnect from ssid FRITZ!Box, reason 201
   reconnect
   scandone
.......   infinite loop

**Comment by martin-ger** [comment]
On the CLI write:
set ssid FRITZ!Box\ 3272


Am 31. Januar 2018 8:19:58 nachm. schrieb Marco Sillano 
<notifications@github.com>:

**Comment by msillano** [comment]
thanks,  the workaround woked :)

Best regards, 
m.s.
