### ISSUE TITLE
Password length limit?

### ISSUE THREAD

**Issue by bilogic** [martin-ger/esp_mqtt#30]
Hi,

Is there a limit on the password length for mqtt_password?
I'm trying to add a remote mqtt broker, it always has 1 missing character in the password after ```set mqtt_password```

**Comment by martin-ger** [comment]
Max length is 31 chars. Do you need more?

**Comment by bilogic** [comment]
Hi, I was using io.adafruit.com and their password is fixed at 32 characters.
I'm trying something else now, thought I just check to be sure. Thank you.
