### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by jnherm** [martin-ger/esp_mqtt#32]
Hello Martin,
Is it possible to assign static IP address on your firmware? What is the console command to do so?

**Comment by martin-ger** [comment]
You can set a fixed network config manually with:

- set ip ip-addr: sets a static IP address for the ESP in the uplink network
- set netmask netmask: sets a static netmask for the uplink network
- set gw gw-addr: sets a static gateway address in the uplink network
- set dns dns-addr: sets a static DNS address

Don't forget the "save" afterwards.
