### ISSUE TITLE
Alarms per day

### ISSUE THREAD

**Issue by b-fork** [martin-ger/esp_mqtt#45]
Awesome project! 

Is there any way to set alarms per day in the script? Something like:
 setalarm 1 "Fri 20:45"
 setalarm 2 "Mon 21:45"
...

And/or to get the current day programmatically in the script? So as to make the choice there.

Thanks

**Comment by martin-ger** [comment]
You can check the $weekday variable in a script.

Am 7. September 2018 13:53:40 schrieb Bruno <notifications@github.com>:

**Comment by b-fork** [comment]
Great! 
Thanks!
