### ISSUE TITLE
Ability to configure softAP channel?

### ISSUE THREAD

**Issue by robjordan** [martin-ger/esp_mqtt#51]
Brilliant product, thank you very much Martin.

I felt it would be very helpful if there was the ability to configure the WiFi channel that the softAP comes up on. When I bring up esp_mqtt in softAP plus station mode, it causes one device on my WiFi network to drop its network connection. I was hoping one could set a different channel for softAP  vs station.

However I've subsequently learned that its a limitation of the esp8266; it has only one radio, so station and softAP will always be on the same WiFi channel. Permanent restriction then.
https://bbs.espressif.com/viewtopic.php?t=324

**Comment by martin-ger** [comment]
Added:
set ap_channel [1-13]: sets the channel of the SoftAP (default 1)

Channel selection ist quite useful in an AP-only setup.

**Comment by robjordan** [comment]
Thank you!
